# Generated by Django 4.2.6 on 2023-11-30 02:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogger',
            name='password',
            field=models.CharField(default='pass1234', max_length=255),
        ),
    ]
